
package primer;

import java.awt.Color;


public class PRIMER extends javax.swing.JFrame {

   int xMouse,yMouse;
    
    public PRIMER() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LOGONAME = new javax.swing.JLabel();
        HEADER = new javax.swing.JPanel();
        EXITBTN = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        FAVICON = new javax.swing.JLabel();
        TITLE = new javax.swing.JLabel();
        USER = new javax.swing.JLabel();
        userTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        PASS = new javax.swing.JLabel();
        passTxt = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        LoginBTN = new javax.swing.JPanel();
        loginbtnTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LOGONAME.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        LOGONAME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tienda .png"))); // NOI18N
        LOGONAME.setText("jLabel1");
        jPanel1.add(LOGONAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, -4, 890, 850));

        HEADER.setBackground(new java.awt.Color(255, 255, 255));
        HEADER.setForeground(new java.awt.Color(255, 255, 255));
        HEADER.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HEADERMouseDragged(evt);
            }
        });
        HEADER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HEADERMousePressed(evt);
            }
        });

        EXITBTN.setBackground(new java.awt.Color(255, 255, 255));

        exitTxt.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        exitTxt.setForeground(new java.awt.Color(0, 0, 0));
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("X");
        exitTxt.setAlignmentX(0.5F);
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitTxt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout EXITBTNLayout = new javax.swing.GroupLayout(EXITBTN);
        EXITBTN.setLayout(EXITBTNLayout);
        EXITBTNLayout.setHorizontalGroup(
            EXITBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EXITBTNLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        EXITBTNLayout.setVerticalGroup(
            EXITBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout HEADERLayout = new javax.swing.GroupLayout(HEADER);
        HEADER.setLayout(HEADERLayout);
        HEADERLayout.setHorizontalGroup(
            HEADERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HEADERLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(EXITBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1202, Short.MAX_VALUE))
        );
        HEADERLayout.setVerticalGroup(
            HEADERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HEADERLayout.createSequentialGroup()
                .addComponent(EXITBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        jPanel1.add(HEADER, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 70));

        FAVICON.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        FAVICON.setForeground(new java.awt.Color(0, 0, 0));
        FAVICON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/favicon.png"))); // NOI18N
        FAVICON.setText("FMOcc");
        jPanel1.add(FAVICON, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 150, 50));

        TITLE.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        TITLE.setForeground(new java.awt.Color(0, 0, 0));
        TITLE.setText("INICIAR SESIÓN");
        jPanel1.add(TITLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 190, 40));

        USER.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        USER.setForeground(new java.awt.Color(0, 0, 0));
        USER.setText("USUARIO");
        jPanel1.add(USER, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 90, 40));

        userTxt.setBackground(new java.awt.Color(255, 255, 255));
        userTxt.setFont(new java.awt.Font("Roboto Thin", 0, 14)); // NOI18N
        userTxt.setForeground(new java.awt.Color(153, 153, 153));
        userTxt.setText("INGRESE SU NOMBRE DE USUARIO");
        userTxt.setBorder(null);
        userTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userTxtMousePressed(evt);
            }
        });
        jPanel1.add(userTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 320, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 340, -1));

        PASS.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        PASS.setForeground(new java.awt.Color(0, 0, 0));
        PASS.setText("CONTRASEÑA");
        jPanel1.add(PASS, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 120, 40));

        passTxt.setBackground(new java.awt.Color(255, 255, 255));
        passTxt.setForeground(new java.awt.Color(204, 204, 204));
        passTxt.setText("contraseña");
        passTxt.setBorder(null);
        passTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passTxtMousePressed(evt);
            }
        });
        jPanel1.add(passTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 270, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 350, -1));

        LoginBTN.setBackground(new java.awt.Color(0, 134, 190));

        loginbtnTxt.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        loginbtnTxt.setForeground(new java.awt.Color(255, 255, 255));
        loginbtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginbtnTxt.setText("ENTRAR");
        loginbtnTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginbtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginbtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginbtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginbtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout LoginBTNLayout = new javax.swing.GroupLayout(LoginBTN);
        LoginBTN.setLayout(LoginBTNLayout);
        LoginBTNLayout.setHorizontalGroup(
            LoginBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginbtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        LoginBTNLayout.setVerticalGroup(
            LoginBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginbtnTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(LoginBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 110, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HEADERMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HEADERMousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_HEADERMousePressed

    private void HEADERMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HEADERMouseDragged
        int x= evt.getXOnScreen();
        int y= evt.getYOnScreen();
        this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_HEADERMouseDragged

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitTxtMouseClicked

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        EXITBTN.setBackground(Color.red);
        exitTxt.setForeground(Color.white);
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        EXITBTN.setBackground(Color.white);
        exitTxt.setForeground(Color.black);
    }//GEN-LAST:event_exitTxtMouseExited
        
    
    private void loginbtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtnTxtMouseEntered
        LoginBTN.setBackground(new Color(0,156,223));
        
        
    }//GEN-LAST:event_loginbtnTxtMouseEntered

    private void loginbtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtnTxtMouseExited
        LoginBTN.setBackground(new Color(0,134,190));
    }//GEN-LAST:event_loginbtnTxtMouseExited

    private void userTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTxtMousePressed
         if (userTxt.getText().equals("INGRESE SU NOMBRE DE USUARIO")) {
             userTxt.setText("");
             userTxt.setForeground(Color.black);
        }
         
         if (String.valueOf(passTxt.getPassword()).isEmpty()) {
            passTxt.setText("**********");
                   passTxt.setForeground(Color.gray);
        
        }
    }//GEN-LAST:event_userTxtMousePressed

    private void passTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passTxtMousePressed
            if (String.valueOf(passTxt.getPassword()).equals("**********")); {
                 passTxt.setText("");
                 passTxt.setForeground(Color.black);
        
        }
            if (userTxt.getText().isEmpty()) {
               userTxt.setText("INGRESE SU NOMBRE DE USUARIO");
               userTxt.setForeground(Color.gray);
        }
           
        
       
    }//GEN-LAST:event_passTxtMousePressed

    private void loginbtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtnTxtMouseClicked
        javax.swing.JOptionPane.showMessageDialog(this,"Intento de ingreso con los datos:\nUsuario:"+userTxt.getText()+"\ncontraseña"+String.valueOf(passTxt.getPassword()),"LOGIN",javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_loginbtnTxtMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PRIMER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PRIMER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PRIMER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PRIMER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PRIMER().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EXITBTN;
    private javax.swing.JLabel FAVICON;
    private javax.swing.JPanel HEADER;
    private javax.swing.JLabel LOGONAME;
    private javax.swing.JPanel LoginBTN;
    private javax.swing.JLabel PASS;
    private javax.swing.JLabel TITLE;
    private javax.swing.JLabel USER;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel loginbtnTxt;
    private javax.swing.JPasswordField passTxt;
    private javax.swing.JTextField userTxt;
    // End of variables declaration//GEN-END:variables

    private Object userText() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
